package com.bwsl.plugin

object BwslTokenTypes {
    // Literals & misc
    @JvmField val LINE_COMMENT  = BwslElementType("LINE_COMMENT")
    @JvmField val BLOCK_COMMENT = BwslElementType("BLOCK_COMMENT")
    @JvmField val STRING_LIT    = BwslElementType("STRING_LIT")
    @JvmField val NUMBER_LIT    = BwslElementType("NUMBER_LIT")
    @JvmField val DECORATOR     = BwslElementType("DECORATOR")
    @JvmField val IDENTIFIER    = BwslElementType("IDENTIFIER")

    // Block-structure keywords
    @JvmField val KW_MODULE        = BwslElementType("KW_MODULE")
    @JvmField val KW_PIPELINE      = BwslElementType("KW_PIPELINE")
    @JvmField val KW_PASS          = BwslElementType("KW_PASS")
    @JvmField val KW_VERTEX        = BwslElementType("KW_VERTEX")
    @JvmField val KW_FRAGMENT      = BwslElementType("KW_FRAGMENT")
    @JvmField val KW_COMPUTE       = BwslElementType("KW_COMPUTE")
    @JvmField val KW_COMPUTE_GRAPH = BwslElementType("KW_COMPUTE_GRAPH")
    @JvmField val KW_ATTRIBUTES    = BwslElementType("KW_ATTRIBUTES")
    @JvmField val KW_RESOURCES     = BwslElementType("KW_RESOURCES")
    @JvmField val KW_VARIANTS      = BwslElementType("KW_VARIANTS")
    @JvmField val KW_STRUCT        = BwslElementType("KW_STRUCT")
    @JvmField val KW_ENUM          = BwslElementType("KW_ENUM")
    @JvmField val KW_EVAL          = BwslElementType("KW_EVAL")
    @JvmField val KW_NODE          = BwslElementType("KW_NODE")
    @JvmField val KW_INPUTS        = BwslElementType("KW_INPUTS")
    @JvmField val KW_OUTPUTS       = BwslElementType("KW_OUTPUTS")

    // Control / declaration keywords
    @JvmField val KW_IMPORT      = BwslElementType("KW_IMPORT")
    @JvmField val KW_USING       = BwslElementType("KW_USING")
    @JvmField val KW_AS          = BwslElementType("KW_AS")
    @JvmField val KW_USE         = BwslElementType("KW_USE")
    @JvmField val KW_CONST       = BwslElementType("KW_CONST")
    @JvmField val KW_SHARED      = BwslElementType("KW_SHARED")
    @JvmField val KW_CONSTRAINT  = BwslElementType("KW_CONSTRAINT")
    @JvmField val KW_RULES       = BwslElementType("KW_RULES")
    @JvmField val KW_REQUIRE     = BwslElementType("KW_REQUIRE")
    @JvmField val KW_CONFLICT    = BwslElementType("KW_CONFLICT")
    @JvmField val KW_RETURN      = BwslElementType("KW_RETURN")
    @JvmField val KW_IF          = BwslElementType("KW_IF")
    @JvmField val KW_ELSE        = BwslElementType("KW_ELSE")
    @JvmField val KW_FOR         = BwslElementType("KW_FOR")
    @JvmField val KW_FOREACH     = BwslElementType("KW_FOREACH")
    @JvmField val KW_WHILE       = BwslElementType("KW_WHILE")
    @JvmField val KW_LOOP        = BwslElementType("KW_LOOP")
    @JvmField val KW_SWITCH      = BwslElementType("KW_SWITCH")
    @JvmField val KW_CASE        = BwslElementType("KW_CASE")
    @JvmField val KW_DEFAULT     = BwslElementType("KW_DEFAULT")
    @JvmField val KW_BREAK       = BwslElementType("KW_BREAK")
    @JvmField val KW_SKIP        = BwslElementType("KW_SKIP")
    @JvmField val KW_CONTINUE    = BwslElementType("KW_CONTINUE")
    @JvmField val KW_DISCARD     = BwslElementType("KW_DISCARD")
    @JvmField val KW_IN          = BwslElementType("KW_IN")
    @JvmField val KW_BY          = BwslElementType("KW_BY")
    @JvmField val KW_UNTIL       = BwslElementType("KW_UNTIL")
    @JvmField val KW_NULL        = BwslElementType("KW_NULL")
    @JvmField val KW_TRUE        = BwslElementType("KW_TRUE")
    @JvmField val KW_FALSE       = BwslElementType("KW_FALSE")
    @JvmField val KW_SELF        = BwslElementType("KW_SELF")
    @JvmField val KW_READONLY    = BwslElementType("KW_READONLY")
    @JvmField val KW_READWRITE   = BwslElementType("KW_READWRITE")
    @JvmField val KW_WRITEONLY   = BwslElementType("KW_WRITEONLY")

    // Function-return-type keywords
    @JvmField val KW_VERTEX_FUNCTION   = BwslElementType("KW_VERTEX_FUNCTION")
    @JvmField val KW_FRAGMENT_FUNCTION = BwslElementType("KW_FRAGMENT_FUNCTION")
    @JvmField val KW_COMPUTE_FUNCTION  = BwslElementType("KW_COMPUTE_FUNCTION")
    @JvmField val KW_PASS_BLOCK        = BwslElementType("KW_PASS_BLOCK")

    // Built-in types
    @JvmField val KW_BOOL     = BwslElementType("KW_BOOL")
    @JvmField val KW_INT      = BwslElementType("KW_INT")
    @JvmField val KW_UINT     = BwslElementType("KW_UINT")
    @JvmField val KW_FLOAT    = BwslElementType("KW_FLOAT")
    @JvmField val KW_DOUBLE   = BwslElementType("KW_DOUBLE")
    @JvmField val KW_INT64    = BwslElementType("KW_INT64")
    @JvmField val KW_UINT64   = BwslElementType("KW_UINT64")
    @JvmField val KW_INT2     = BwslElementType("KW_INT2")
    @JvmField val KW_INT3     = BwslElementType("KW_INT3")
    @JvmField val KW_INT4     = BwslElementType("KW_INT4")
    @JvmField val KW_UINT2    = BwslElementType("KW_UINT2")
    @JvmField val KW_UINT3    = BwslElementType("KW_UINT3")
    @JvmField val KW_UINT4    = BwslElementType("KW_UINT4")
    @JvmField val KW_FLOAT2   = BwslElementType("KW_FLOAT2")
    @JvmField val KW_FLOAT3   = BwslElementType("KW_FLOAT3")
    @JvmField val KW_FLOAT4   = BwslElementType("KW_FLOAT4")
    @JvmField val KW_DOUBLE2  = BwslElementType("KW_DOUBLE2")
    @JvmField val KW_DOUBLE3  = BwslElementType("KW_DOUBLE3")
    @JvmField val KW_DOUBLE4  = BwslElementType("KW_DOUBLE4")
    @JvmField val KW_INT64X2  = BwslElementType("KW_INT64X2")
    @JvmField val KW_INT64X3  = BwslElementType("KW_INT64X3")
    @JvmField val KW_INT64X4  = BwslElementType("KW_INT64X4")
    @JvmField val KW_UINT64X2 = BwslElementType("KW_UINT64X2")
    @JvmField val KW_UINT64X3 = BwslElementType("KW_UINT64X3")
    @JvmField val KW_UINT64X4 = BwslElementType("KW_UINT64X4")
    @JvmField val KW_MAT2     = BwslElementType("KW_MAT2")
    @JvmField val KW_MAT3     = BwslElementType("KW_MAT3")
    @JvmField val KW_MAT4     = BwslElementType("KW_MAT4")
    @JvmField val KW_DMAT2    = BwslElementType("KW_DMAT2")
    @JvmField val KW_DMAT3    = BwslElementType("KW_DMAT3")
    @JvmField val KW_DMAT4    = BwslElementType("KW_DMAT4")
    @JvmField val KW_SAMPLER        = BwslElementType("KW_SAMPLER")
    @JvmField val KW_TEXTURE2D      = BwslElementType("KW_TEXTURE2D")
    @JvmField val KW_TEXTURE3D      = BwslElementType("KW_TEXTURE3D")
    @JvmField val KW_TEXTURECUBE    = BwslElementType("KW_TEXTURECUBE")
    @JvmField val KW_TEXTURE2DARRAY = BwslElementType("KW_TEXTURE2DARRAY")
    @JvmField val KW_IMAGE2D        = BwslElementType("KW_IMAGE2D")
    @JvmField val KW_BUFFER         = BwslElementType("KW_BUFFER")
    @JvmField val KW_CBUFFER        = BwslElementType("KW_CBUFFER")
    @JvmField val KW_VOID           = BwslElementType("KW_VOID")

    // Punctuation
    @JvmField val LBRACE     = BwslElementType("LBRACE")
    @JvmField val RBRACE     = BwslElementType("RBRACE")
    @JvmField val LPAREN     = BwslElementType("LPAREN")
    @JvmField val RPAREN     = BwslElementType("RPAREN")
    @JvmField val LBRACKET   = BwslElementType("LBRACKET")
    @JvmField val RBRACKET   = BwslElementType("RBRACKET")
    @JvmField val SEMI       = BwslElementType("SEMI")
    @JvmField val COMMA      = BwslElementType("COMMA")
    @JvmField val QUESTION   = BwslElementType("QUESTION")
    @JvmField val DOTDOTEQ   = BwslElementType("DOTDOTEQ")
    @JvmField val DOTDOT     = BwslElementType("DOTDOT")
    @JvmField val DOT        = BwslElementType("DOT")
    @JvmField val COLONCOLON = BwslElementType("COLONCOLON")
    @JvmField val COLON      = BwslElementType("COLON")
    @JvmField val ARROW      = BwslElementType("ARROW")

    // Operators
    @JvmField val LSHIFTEQ   = BwslElementType("LSHIFTEQ")
    @JvmField val RSHIFTEQ   = BwslElementType("RSHIFTEQ")
    @JvmField val LSHIFT     = BwslElementType("LSHIFT")
    @JvmField val RSHIFT     = BwslElementType("RSHIFT")
    @JvmField val LE         = BwslElementType("LE")
    @JvmField val GE         = BwslElementType("GE")
    @JvmField val EQEQ       = BwslElementType("EQEQ")
    @JvmField val NEQ        = BwslElementType("NEQ")
    @JvmField val AND        = BwslElementType("AND")
    @JvmField val OR         = BwslElementType("OR")
    @JvmField val PLUSPLUS   = BwslElementType("PLUSPLUS")
    @JvmField val MINUSMINUS = BwslElementType("MINUSMINUS")
    @JvmField val PLUSEQ     = BwslElementType("PLUSEQ")
    @JvmField val MINUSEQ    = BwslElementType("MINUSEQ")
    @JvmField val STAREQ     = BwslElementType("STAREQ")
    @JvmField val SLASHEQ    = BwslElementType("SLASHEQ")
    @JvmField val PERCENTEQ  = BwslElementType("PERCENTEQ")
    @JvmField val AMPEQ      = BwslElementType("AMPEQ")
    @JvmField val PIPEEQ     = BwslElementType("PIPEEQ")
    @JvmField val CARETEQ    = BwslElementType("CARETEQ")
    @JvmField val LT         = BwslElementType("LT")
    @JvmField val GT         = BwslElementType("GT")
    @JvmField val EQ         = BwslElementType("EQ")
    @JvmField val PLUS       = BwslElementType("PLUS")
    @JvmField val MINUS      = BwslElementType("MINUS")
    @JvmField val STAR       = BwslElementType("STAR")
    @JvmField val SLASH      = BwslElementType("SLASH")
    @JvmField val PERCENT    = BwslElementType("PERCENT")
    @JvmField val AMP        = BwslElementType("AMP")
    @JvmField val PIPE       = BwslElementType("PIPE")
    @JvmField val CARET      = BwslElementType("CARET")
    @JvmField val TILDE      = BwslElementType("TILDE")
    @JvmField val BANG       = BwslElementType("BANG")
}
